node {   
    stage('cleanup workspace') {
           sh '''#!/bin/bash
           rm -fr *
           '''
    }
    stage('get yocto project files from github') {
           sh '''#!/bin/bash
           git clone git://git.yoctoproject.org/poky -b pyro
           '''
    }
    stage('build') {
           sh '''#!/bin/bash
           rm -fr build 
           source oe-init-build-env
           ln -s ~/.yoctoshare/downloads ./downloads
           ln -s ~/.yoctoshare/sstate-cache ./sstate-cache
           bitbake core-image-minimal
           make
           '''
    }
 }
