node{   
    stage('cleanup workspace') {
           sh '''#!/bin/bash
           rm -fr *
           '''
    }
    stage('get yocto project files from github') {
           sh '''#!/bin/bash
		git clone -b rocko git://git.yoctoproject.org/poky.git poky-rocko
		cd poky-rocko
		git clone -b rocko git://git.openembedded.org/meta-openembedded
		git clone -b rocko https://github.com/meta-qt5/meta-qt5
		git clone -b rocko git://git.yoctoproject.org/meta-security
		git clone -b rocko git://git.yoctoproject.org/meta-raspberrypi
		set MACHINE="raspberrypi3"
		source oe-init-build-env build
           '''
    }
    stage('build') {
           sh '''#!/bin/bash
		cd poky-rocko
		source oe-init-build-env build
		ln -s ~/.yoctoshare/downloads ./downloads
		ln -s ~/.yoctoshare/sstate-cache ./sstate-cache
		bitbake core-image-base
           '''
    }
 }
